eos:
  aloha_id: 1
  big_block_transactions: 1759
  chain_id: aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 1
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: EOS
  filename: bp.json
  location_check: country
  maintainer: matthew
  max_producers: 150
  name: eos
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 0
  sort_order: 100
  test_account: eosnationftw
  test_big_block: 185835674
  test_bpjson_code: producerjson
  test_bpjson_scope: producerjson
  test_bpjson_table: producerjson
  test_public_key: EOS7w5aJCv5B7y3a6f4WCwPSvs6TpCAoRGnGpiLMsSWbmxaZdKigd
  test_transaction: 1bc395276f4bdde15a7992e50e61938457673e861d9480b51762b6e4457e5b79
  url: http://eos.api.eosnation.io

jungle4:
  aloha_id: ''
  big_block_transactions: ''
  chain_id: 73e4385a2708e6d7048834fbc1079f2fabb17b3c125b146af438971e90716c4d
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 1
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: EOS
  filename: jungle4.json
  location_check: timezone100
  maintainer: matthew
  max_producers: 150
  name: jungle4
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 180
  sort_order: 900
  test_account: eosnationftw
  test_big_block: 1025382
  test_bpjson_code: producerjson
  test_bpjson_scope: producerjson
  test_bpjson_table: producerjson
  test_public_key: EOS4uP4oHhtVyZAQze1qMY7ZKqof3y26L6bvnr2FfpMJhhvAnEr1v
  test_transaction: 4d458e04a592656b1ff572c8584723106a433c12d96aaca7caec6f20bad251c9
  url: http://jungle4.api.eosnation.io

kylin:
  aloha_id: 3
  big_block_transactions: 1506
  chain_id: 5fff1dae8dc8e2fc4d5b23b2c7665c97f9e9d8edf2b6485a86ba311c25639191
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 1
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: EOS
  filename: kylin.json
  location_check: country
  maintainer: matthew
  max_producers: 150
  name: kylin
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 0
  sort_order: 902
  test_account: eosnationftw
  test_big_block: 29763179
  test_bpjson_code: producerjson
  test_bpjson_scope: producerjson
  test_bpjson_table: producerjson
  test_public_key: EOS7w5aJCv5B7y3a6f4WCwPSvs6TpCAoRGnGpiLMsSWbmxaZdKigd
  test_transaction: f680f985421df7e04edba774b82f90b58ea7cf2479015eaed6d04c05634323ac
  url: http://kylin.api.eosnation.io

telos:
  aloha_id: 5
  big_block_transactions: 778
  chain_id: 4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 1
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: TLOS
  filename: bp.json
  location_check: none
  maintainer: michael
  max_producers: 150
  name: telos
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 0
  sort_order: 110
  test_account: votetelosusa
  test_big_block: 39276879
  test_bpjson_code: producerjson
  test_bpjson_scope: producerjson
  test_bpjson_table: producerjson
  test_public_key: EOS7avuePJFiLEaKbziUBs21CyVJn6hN3KHiEjeMnSKGiT3VvMvzz
  test_transaction: f3b8bc689d97d9e9ec89881c471f73dcba8287b64046f74d1aeded17de83b43e
  url: http://telos.api.eosnation.io

telostest:
  aloha_id: 13
  big_block_transactions: 34
  chain_id: 1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f3195f33c9f
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 0
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: TLOS
  filename: bp.json
  location_check: none
  maintainer: michael
  max_producers: 150
  name: telostest
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 0
  sort_order: 907
  test_account: nation.tlos
  test_big_block: 63289201
  test_bpjson_code: ''
  test_bpjson_scope: ''
  test_bpjson_table: ''
  test_public_key: EOS5NibtcPBxeCs6qMRgjs6ixxT6QMtjWmifYHwM5srhL2f3oknbd
  test_transaction: f3b8bc689d97d9e9ec89881c471f73dcba8287b64046f74d1aeded17de83b43e
  url: http://telostest.api.eosnation.io

ux:
  aloha_id: ''
  big_block_transactions: ''
  chain_id: 8fc6dce7942189f842170de953932b1f66693ad3788f766e777b6f9d22335c02
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 0
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: UTX
  filename: ux.json
  location_check: none
  maintainer: matthew
  max_producers: 150
  name: ux
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 0
  sort_order: 120
  test_account: nation.ux
  test_big_block: 999999
  test_bpjson_code: producerjson
  test_bpjson_scope: producerjson
  test_bpjson_table: producerjson
  test_public_key: EOS7w5aJCv5B7y3a6f4WCwPSvs6TpCAoRGnGpiLMsSWbmxaZdKigd
  test_transaction: 26ca258e963137625375197becb6160450cfc4b58f26775ebf273cb83e47f6b8
  url: http://ux.api.eosnation.io

wax:
  aloha_id: 11
  big_block_transactions: 76
  chain_id: 1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 1
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: WAX
  filename: wax.json
  location_check: none
  maintainer: matthew
  max_producers: 150
  name: wax
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 0
  sort_order: 103
  test_account: nation.wax
  test_big_block: 7846307
  test_bpjson_code: producerjson
  test_bpjson_scope: producerjson
  test_bpjson_table: producerjson
  test_public_key: EOS7w5aJCv5B7y3a6f4WCwPSvs6TpCAoRGnGpiLMsSWbmxaZdKigd
  test_transaction: 26ca258e963137625375197becb6160450cfc4b58f26775ebf273cb83e47f6b8
  url: http://wax.api.eosnation.io

waxtest:
  aloha_id: 16
  big_block_transactions: ''
  chain_id: f16b1833c747c43682f4386fca9cbb327929334a762755ebec17f6f23c9b8a12
  class_account: 1
  class_api_endpoint: 1
  class_atomic: 1
  class_blocks: 1
  class_bpjson: 1
  class_chains: 1
  class_dfuse: 1
  class_firehose: 1
  class_history: 1
  class_hyperion: 1
  class_ipv6: 0
  class_org: 1
  class_p2p_endpoint: 1
  class_regproducer: 1
  core_symbol: WAX
  filename: waxtest.json
  location_check: none
  maintainer: matthew
  max_producers: 150
  name: waxtest
  report_api_versions: 150
  report_branding: 140
  report_config: 190
  report_country: 170
  report_endpoints: 110
  report_errors: 200
  report_p2p_speed: 0
  report_resources: 120
  report_socials: 130
  report_timezone: 0
  sort_order: 906
  test_account: nation.wax
  test_big_block: ''
  test_bpjson_code: producerjson
  test_bpjson_scope: producerjson
  test_bpjson_table: producerjson
  test_public_key: EOS7w5aJCv5B7y3a6f4WCwPSvs6TpCAoRGnGpiLMsSWbmxaZdKigd
  test_transaction: 4ccaf948d717e2d705ba23079ce77676bcf32daa9f98317f112f9011414a61d3
  url: http://waxtest.api.eosnation.io
