v3.1.0wax01:
  api_current: 0
  hash: v3.1.0wax01
  name: 3.1.0
v3.1.1wax01:
  api_current: 0
  hash: v3.1.1wax01
  name: 3.1.1
v3.1.2wax01:
  api_current: 0
  hash: v3.1.2wax01
  name: 3.1.2
v3.1.3wax01:
  api_current: 0
  hash: v3.1.3wax01
  name: 3.1.3
v3.1.4wax01:
  api_current: 0
  hash: v3.1.4wax01
  name: 3.1.4
v3.1.4wax02:
  api_current: 0
  hash: v3.1.4wax02
  name: 3.1.4
v3.1.4wax02-hotfix:
  api_current: 0
  hash: v3.1.4wax02-hotfix
  name: 3.1.4
v3.1.4:
  api_current: 0
  hash: v3.1.4
  name: 3.1.4
v3.1.5wax01:
  api_current: 0
  hash: v3.1.5wax01
  name: 3.1.5
v3.1.6wax01:
  api_current: 0
  hash: v3.1.6wax01
  name: 3.1.6
v3.2.0wax01:
  api_current: 0
  hash: v3.2.0wax01
  name: 3.2.0
v3.2.1wax01:
  api_current: 0
  hash: v3.2.1wax01
  name: 3.2.1
v3.2.2wax01:
  api_current: 0
  hash: v3.2.2wax01
  name: 3.2.2
v3.2.3wax01:
  api_current: 0
  hash: v3.2.3wax01
  name: 3.2.3
v3.2.3wax01-hotfix:
  api_current: 1
  hash: v3.2.3wax01-hotfix
  name: 3.2.3
v3.2.4wax01:
  api_current: 1
  hash: v3.2.4wax01
  name: 3.2.4
v3.2.5wax01:
  api_current: 1
  hash: v3.2.5wax01
  name: 3.2.5
v3.2.6wax01:
  api_current: 1
  hash: v3.2.6wax01
  name: 3.2.6
v4.0.0wax01:
  api_current: 0
  hash: v4.0.0wax01
  name: 4.0.0
v4.0.1wax01:
  api_current: 0
  hash: v4.0.1wax01
  name: 4.0.1
v4.0.1wax01-hotfix:
  api_current: 1
  hash: v4.0.1wax01-hotfix
  name: 4.0.1
v4.0.2wax01:
  api_current: 0
  hash: v4.0.2wax01
  name: 4.0.2
v4.0.3wax01:
  api_current: 0
  hash: v4.0.3wax01
  name: 4.0.3
v4.0.4wax01:
  api_current: 1
  hash: v4.0.4wax01
  name: 4.0.4
v4.0.5wax01:
  api_current: 1
  hash: v4.0.5wax01
  name: 4.0.5
v4.0.6wax01:
  api_current: 1
  hash: v4.0.6wax01
  name: 4.0.6
v5.0.0wax01-rc3:
  api_current: 1
  hash: v5.0.0wax01
  name: 5.0.0
v5.0.0wax01:
  api_current: 1
  hash: v5.0.0wax01
  name: 5.0.0
