v1.0.0-rc1:
  api_current: 0
  hash: v1.0.0-rc1
  name: 1.0.0 (spring)
v1.0.0-rc2:
  api_current: 0
  hash: v1.0.0-rc2
  name: 1.0.0 (spring)
v1.0.0-rc3:
  api_current: 0
  hash: v1.0.0-rc3
  name: 1.0.0 (spring)
v1.0.0:
  api_current: 0
  hash: v1.0.0
  name: 1.0.0 (spring)
v1.0.1:
  api_current: 0
  hash: v1.0.1
  name: 1.0.1 (spring)
v1.0.2:
  api_current: 0
  hash: v1.0.2
  name: 1.0.2 (spring)
v1.0.3:
  api_current: 0
  hash: v1.0.3
  name: 1.0.3 (spring)
v1.0.4:
  api_current: 0
  hash: v1.0.4
  name: 1.0.4 (spring)
v1.0.5:
  api_current: 1
  hash: v1.0.5
  name: 1.0.5 (spring)
v1.0.6:
  api_current: 1
  hash: v1.0.6
  name: 1.0.6 (spring)
v1.0.7:
  api_current: 1
  hash: v1.0.7
  name: 1.0.7 (spring)
v1.1.0-rc1:
  api_current: 0
  hash: v1.1.0-rc1
  name: 1.1.0 (spring)
v1.1.0-rc2:
  api_current: 0
  hash: v1.1.0-rc2
  name: 1.1.0 (spring)
v1.1.0:
  api_current: 0
  hash: v1.1.0
  name: 1.1.0 (spring)
v1.1.1:
  api_current: 0
  hash: v1.1.1
  name: 1.1.1 (spring)
v1.1.2:
  api_current: 1
  hash: v1.1.2
  name: 1.1.2 (spring)
v1.1.3:
  api_current: 1
  hash: v1.1.3
  name: 1.1.3 (spring)
v1.1.4:
  api_current: 1
  hash: v1.1.4
  name: 1.1.4 (spring)
v1.1.5:
  api_current: 1
  hash: v1.1.5
  name: 1.1.5 (spring)
v1.2.0-rc1:
  api_current: 0
  hash: v1.2.0-rc1
  name: 1.2.0 (spring)
v1.2.0-rc2:
  api_current: 0
  hash: v1.2.0-rc2
  name: 1.2.0 (spring)
v1.2.0:
  api_current: 1
  hash: v1.2.0
  name: 1.2.0 (spring)
v1.2.1:
  api_current: 1
  hash: v1.2.1
  name: 1.2.1 (spring)
v1.2.2:
  api_current: 1
  hash: v1.2.2
  name: 1.2.2 (spring)
