v3.0.10:
  api_current: 1
  hash: v3.0.10
  name: bos-3.0.10
v3.0.11:
  api_current: 1
  hash: v3.0.11
  name: bos-3.0.11
v3.0.2:
  api_current: 0
  hash: v3.0.2
  name: bos-3.0.2
v3.0.3:
  api_current: 0
  hash: v3.0.3
  name: bos-3.0.3
v3.0.4:
  api_current: 0
  hash: v3.0.4
  name: bos-3.0.4
v3.0.5:
  api_current: 0
  hash: v3.0.5
  name: bos-3.0.5
v3.0.6:
  api_current: 0
  hash: v3.0.6
  name: bos-3.0.6
v3.0.7:
  api_current: 0
  hash: v3.0.7
  name: bos-3.0.7
v3.0.8:
  api_current: 1
  hash: v3.0.8
  name: bos-3.0.8
v3.0.9:
  api_current: 1
  hash: v3.0.9
  name: bos-3.0.9
v3.1.0:
  api_current: 1
  hash: v3.1.0
  name: bos-3.1.0
